### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by kubatatami** [escamoteur/super_tooltip#18]
Thanks for the great package!

Do you plan to make a null safe update of the package?

**Comment by escamoteur** [comment]
Just pushed V1.0.0

**Comment by BaranMichal25** [comment]
on that note, I'm getting:
```
I/flutter (10765): FLUTTER ERROR: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 134 pos 12: '_overlay != null': is not true.
I/flutter (10765): #2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:134:12)
I/flutter (10765): #3      SuperTooltip.close (package:super_tooltip/super_tooltip.dart:196:20)
I/flutter (10765): #4      _RotateTipWrapperState.initState.<anonymous closure> (package:trainr_mobile/features/workout/widgets/workout_rotate_tip.dart:44:17)
I/flutter (10765): (elided 14 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

so I'm guessing there should be `?` instead of `!` here: https://github.com/escamoteur/super_tooltip/blob/master/lib/super_tooltip.dart#L199

This happens when I tap somewhere outside the Tooltip to close it.

**Comment by BaranMichal25** [comment]
on that note, I'm getting:
```
I/flutter (10765): FLUTTER ERROR: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 134 pos 12: '_overlay != null': is not true.
I/flutter (10765): #2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:134:12)
I/flutter (10765): #3      SuperTooltip.close (package:super_tooltip/super_tooltip.dart:196:20)
I/flutter (10765): #4      _RotateTipWrapperState.initState.<anonymous closure> (package:xxxx/features/xxx/yyy/workout_rotate_tip.dart:44:17)
I/flutter (10765): (elided 14 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

so I'm guessing there should be `?` instead of `!` here: https://github.com/escamoteur/super_tooltip/blob/master/lib/super_tooltip.dart#L199

This happens when I tap somewhere outside the Tooltip to close it.
